# this is python script and i am learning FilesIO in python...
"""
There exist two types of files,
    1 -> text file (.txt)
    2 -> binary files (.jpeg, .png, .pdf, etc...)

Python has lots of functions to read, update or delete the files...
    1 -> Opening a file
        => for opening a file in python, we have open(<file_name>, <mode>) function
            -> <file_name> : the name of the file, which we want to read...
            -> <mode> : the mode, specifies the operation for which we want to open a file <file_name>
                ex. read -> 'r', append -> 'a', write -> 'w', updating/(read + write) -> '+'

    2 -> reading a file
        => after opening a file, if we didn't pass the <mode> argument then, file will be opened in 'r' mode...
        => or else we can explicitly mention <mode> argument = 'r'...
        => then after we can use either of the below function to read the data from the file...
            -> <file>.read() will read entire file...
                -> or else we can explicitly mention numbers of characters that we want to read from the file...
                    ex. <file>.read(n) -> it will read first 'n' characters from the file...
            -> <file>.readLine() will read the one line from the file...

    3 -> writing to file
        => we can open a file in either 'w' mode, 'a' mode or '+' mode so that we can perform writing operation to file
        => if we open a file in 'w' mode
            -> all the previous contents of the file will be deleted, and then we can perform writing to file...
        => if we open a file in 'a' or '+' mode
            -> the data which was there in file previously, will not be deleted...
        => we can use below function to write to file...
            -> <file>.write(<string_data_that_we_want_to_write>)

    4 -> closing a file
        => after performing the operations on opened file, we must need to close the file; which was opened by us.
        => It acts as 'commit' statements, assuring that whatever we have changed till now; that all the changes
            will be made to or applied to the file...
        => we can close the file...
            -> by using <file>.close()....

    5 -> the best way to open or close the file...
        => we can use 'with' statement as shown below...it will automatically close the file, which was opened...
            ex.
                with open(<file_name>, <mode>) as <variable_name>:
                    <operations_that_we_want_to_perform>
                    ...
                    ...

        => after the end of 'with' block, the file will be closed...

"""

# by default the mode of the open() func. is 'r' ... ===================================================================
file = open("Sample.txt")
# data = file.read()  # we can use number of characters in arguments, to read 'n' character from file...mentioned
# below...
characters = 10
data = file.read(characters)
file.close()
print("First", characters, "Characters : ", data)
# we can also use a readLine() function to read one line from the file...

# writing to file...
file1 = open("TestFile.txt", 'a')
file1.write("\nThis line was added by the help of python!")
file1.close()

# best way to open and close the file...
with open("TestFile.txt", 'r+') as file:
    # contents = file.read()
    file.write("This line was added by Henil Mistry by using python script!")
    contents = file.read()
    print(contents)

