"""

I have created this file,
to convert the .png file to .pdf file....

"""

from PIL import Image  # importing the module...

# getting the image file...
# you may need to change the path...
image_1 = Image.open(r'D:\Project\Python\Assignment_Files\Assignment_10\UniversityResult.png')
# getting the abstract data from .png file...
img_1 = image_1.convert('RGB')
# creating .pdf file from the data...
img_1.save(r'D:\Project\Python\Assignment_Files\Assignment_10\HenilResult.pdf')